AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: aws-lambda-rest example for pets endpoints

Resources:
  MinimalResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.andrewohara.minimal.MinimalResource
        Runtime: java8
        CodeUri: ./kobaltBuild/libs/example-pets-0.0.1.jar
        Timeout: 30
        MemorySize: 1024
        Events:
          GetPerson:
            Type: Api
            Properties:
              Path: /people/{id}
              Method: get

  PetsResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.andrewohara.pets.PetsResource
      Runtime: java8
      CodeUri: ./kobaltBuild/libs/example-pets-0.0.1.jar
      Timeout: 30
      MemorySize: 1024
      Events:
        Pets:
          Type: Api
          Properties:
            Path: /pets
            Method: any
        Pet:
          Type: Api
          Properties:
            Path: /pets/{petId}
            Method: any

  PetsResourcePermission:  # This is required because of a bug in AWS SAM when using the "Any" Method on api events
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PetsResource
      Principal: apigateway.amazonaws.com